sudo: required
dist: trusty
language: c

matrix:
  include:
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

node_js:
  - 6

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - icnsutils
      - graphicsmagick
      - libgnome-keyring-dev
      - xz-utils
      - xorriso
      - xvfb

install:
  - nvm install 6
  - npm install electron -g
  - npm install electron-builder -g
  - npm install
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  - electron-builder --linux deb tar.xz

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FS9BMhWZXdTblOVCwPYMxVAowP/NYPa7vlS+kBKqUvF4M0iItcLG6mfHqYIvgKq6/j+drPDU+6f+DcCv0vDzYeA3LkWzos+ORK+dzmD9ByWn+ywJiEA5Yo0wKfIwmbS0uvn6mK5l7jnMIveUTonLan5Qoa4ZeGu7N7ez9EPARmtWk6bch2Lp+YS7ldu21j1s4NmqBHr1F+PmOS0+DjPA88Thfnzo/eRv2WOZbeei2s8+/j0C07FB6n/h1zxEbikqIvqUkCc0maku9NJIDUSaFv/DS2G3RRu8kACAEsSsORhWuFYxQwluUObwM1yrvnVJ8i8BfIIkSUMisMiUQod4piexev7RZYnnwsQU2W+0t4NXj5vDAZipRQ+7/GWT5BTNTx1QSSLdWB6P1SpRi2Lc9eN5QD9CJG5tNOxrhECJBAFQMVk57wKskZi2415IGUMjMjG2Ou+nr8nSA66egUIpLx7R+So7xHeU8PdDBjJnh2Fn1G4lMbHtfj9m8HGtrr0E6QdAapbuHPLxxStg3gyMmQ0ZPzkH+Iz7yxdQcr4qdjZxVUNZpgs689a1LMkuG0nbwfqF2F4jinHtIw5yniyZ8yuAJNedKCessE6Q8w7DzvifwyxVOBQ9eRGhr9onScXgkIHOAsPJRep60uvn8ZpJC2aZTRCzOWEk6ISjj53ndHc=
  file: dist/*
  on:
    repo: iblacksand/custompadlock
